//! Contract for Spec #407: Telemetry Metrics (Phase 2)
//!
//! This file defines the type-level contracts that all capsules must satisfy.
//! Coders implement against these stubs; the compiler catches type mismatches.
//!
//! Generated by Architect — do not modify. Capsules may extend but must keep these signatures.

use std::sync::{Arc, AtomicBool, Mutex};
use std::time::Instant;

use anyhow::Result;
use serde::{Deserialize, Serialize};

// Forward references — actual types from the codebase.
pub use crate::infrastructure::comm::event::FredoEvent;
pub use crate::infrastructure::storage::span_store::SpanStore;
pub use crate::infrastructure::storage::AppStore;

// ── MetricPoint ────────────────────────────────────────────────────────────────

/// A single pre-aggregated metric data point written to telemetry_metrics.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MetricPoint {
    pub metric_name: String,
    pub metric_type: MetricType,
    pub labels_json: String,
    pub value: f64,
    pub timestamp: String,
    pub aggregation_window_s: i64,
}

// ── MetricType ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MetricType {
    Counter,
    Gauge,
    Histogram,
}

// ── MetricCollector contract ───────────────────────────────────────────────────

/// REQ-1 through REQ-8, REQ-13, REQ-17, REQ-18:
/// MetricCollector observes FredoEvents in parallel with SpanCollector.
pub struct MetricCollector {
    pub(crate) store: Arc<SpanStore>,
    pub(crate) app_store: Arc<AppStore>,
    pub(crate) inner: Mutex<CollectorInner>,
    pub(crate) enabled_cache: AtomicBool,
}

pub(crate) struct CollectorInner {
    // REQ-2: counters by label_key -> value
    pub(crate) counters: std::collections::HashMap<String, u64>,
    // REQ-6: histograms by span_name -> bucket_counts
    pub(crate) histograms: std::collections::HashMap<String, [u64; HISTOGRAM_BUCKET_COUNT]>,
    // REQ-5: active session IDs
    pub(crate) active_sessions: std::collections::HashSet<String>,
    // REQ-3: events_received per (event_type, transport)
    pub(crate) events_received: std::collections::HashMap<String, u64>,
    // Flush timer
    pub(crate) last_flush: Instant,
    // Completion tracking: span start times for duration calculation
    pub(crate) span_starts: std::collections::HashMap<String, Instant>,
}

impl MetricCollector {
    pub fn new(store: Arc<SpanStore>, app_store: Arc<AppStore>) -> Self {
        let enabled = app_store
            .get("tracing.metrics_enabled")
            .ok()
            .flatten()
            .map(|v| v == "true")
            .unwrap_or(true);

        MetricCollector {
            store,
            app_store,
            inner: Mutex::new(CollectorInner {
                counters: std::collections::HashMap::new(),
                histograms: std::collections::HashMap::new(),
                active_sessions: std::collections::HashSet::new(),
                events_received: std::collections::HashMap::new(),
                last_flush: Instant::now(),
                span_starts: std::collections::HashMap::new(),
            }),
            enabled_cache: AtomicBool::new(enabled),
        }
    }

    pub fn refresh_enabled(&self) {
        let enabled = self
            .app_store
            .get("tracing.metrics_enabled")
            .ok()
            .flatten()
            .map(|v| v == "true")
            .unwrap_or(true);
        self.enabled_cache
            .store(enabled, std::sync::atomic::Ordering::SeqCst);
    }

    /// REQ-13: Toggle-off flushes remaining metrics before stopping.
    pub fn disable_and_flush(&self) -> u64 {
        self.enabled_cache
            .store(false, std::sync::atomic::Ordering::SeqCst);
        self.flush_all()
    }

    /// REQ-1,2,3,5,6: Process FredoEvents to derive metrics.
    pub fn process_events(&self, events: &[FredoEvent]) {
        todo!("Implement in Capsule A")
    }

    /// REQ-4: Record swept orphan count from SpanCollector.
    pub fn record_orphan_count(&self, count: u64) {
        todo!("Implement in Capsule A")
    }

    /// REQ-8,17: Flush if aggregation window elapsed.
    pub fn flush_if_needed(&self) -> u64 {
        todo!("Implement in Capsule A")
    }

    /// REQ-18: Force-flush all buffered metrics.
    pub fn flush_all(&self) -> u64 {
        todo!("Implement in Capsule A")
    }

    /// REQ-5: Current active session count.
    pub fn active_session_count(&self) -> u64 {
        todo!("Implement in Capsule A")
    }
}

// ── Histogram constants ────────────────────────────────────────────────────────

/// REQ-6: Histogram bucket boundaries in milliseconds.
pub const HISTOGRAM_BUCKETS_MS: [u64; 12] = [
    1, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000,
];

/// Number of histogram buckets (12 boundaries → 13 buckets: one per boundary + +Inf).
pub const HISTOGRAM_BUCKET_COUNT: usize = 13;

// ── SpanStore extension contract ───────────────────────────────────────────────

/// Implemented by SpanStore. Capsule A calls these during flush; Capsule B provides the impl.
pub trait SpanStoreMetricsExt {
    /// REQ-9: Create telemetry_metrics table and indexes.
    fn ensure_metrics_schema(&self) -> Result<()>;

    /// REQ-10: Batch-insert pre-aggregated metric points.
    fn insert_metrics(&self, points: &[MetricPoint]) -> Result<usize>;

    /// Stats for telemetry_metrics: (point_count, storage_bytes).
    fn metric_stats(&self) -> Result<(u64, u64)>;

    /// REQ-11: Delete expired metric points.
    fn delete_metrics_expired(&self, retention_days: i64) -> Result<u64>;

    /// REQ-12: Delete all metric points.
    fn purge_metrics(&self) -> Result<u64>;
}
