# E2E verification tests for OpenCode replacement (Spec #5)
# Verifies AC-1 through AC-12 from the spec
# Generated by @fredo-tester

param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..'))
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:passed = 0
$script:failed = 0
$script:results = @()

function Assert-True {
  param([bool]$Condition, [string]$Message, [string]$AC = '', [string]$Evidence = '')
  if ($Condition) {
    $script:passed++
    $script:results += @{ AC = $AC; Status = 'PASS'; Message = $Message; Evidence = $Evidence }
    Write-Host "  PASS: $Message" -ForegroundColor Green
  } else {
    $script:failed++
    $script:results += @{ AC = $AC; Status = 'FAIL'; Message = $Message; Evidence = $Evidence }
    Write-Host "  FAIL: $Message" -ForegroundColor Red
  }
}

function Search-InFiles {
  param(
    [string]$Pattern,
    [string[]]$Extensions,
    [string]$Directory,
    [string[]]$ExcludeDirs = @()
  )
  $hits = @()
  $files = Get-ChildItem -LiteralPath $Directory -Recurse -File -ErrorAction SilentlyContinue
  foreach ($f in $files) {
    $ext = $f.Extension.ToLower()
    if ($Extensions -notcontains $ext) { continue }
    $excluded = $false
    foreach ($ex in $ExcludeDirs) {
      if ($f.FullName -like "*$ex*") { $excluded = $true; break }
    }
    if ($excluded) { continue }
    $content = Get-Content $f.FullName -Raw -ErrorAction SilentlyContinue
    if (-not $content) { continue }
    $matches = [regex]::Matches($content, $Pattern, [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
    if ($matches.Count -gt 0) {
      $hits += @{ File = $f.FullName; Count = $matches.Count; Lines = @() }
      foreach ($m in $matches) {
        $lineNum = (Get-Content $f.FullName | Select-String -Pattern $Pattern -SimpleMatch:$false | Select-Object -First 3).LineNumber
      }
    }
  }
  return $hits
}

$rustSrcDir = Join-Path $RepoRoot 'apps\tauri\src-tauri\src'
$uiSrcDir = Join-Path $RepoRoot 'apps\ui\src'
$docsDir = Join-Path $RepoRoot 'docs'
$marketplaceDir = Join-Path $RepoRoot 'apps\marketplace-plugin'

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " OpenCode Replacement Verification Tests" -ForegroundColor Cyan
Write-Host " Spec: #5  |  PR: #14 (merged)" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ── AC-1: No copilot/claude references in source code ──────────────────────

Write-Host "--- AC-1: No copilot/claude references in source code ---" -ForegroundColor Yellow

# Check Rust source
$rustHits = Search-InFiles -Pattern '\bcopilot\b|\bclaude\b' -Extensions @('.rs') -Directory $rustSrcDir -ExcludeDirs @('target')
$rustHitCount = ($rustHits | Measure-Object).Count
Assert-True -Condition ($rustHitCount -eq 0) -Message "Rust source has no copilot/claude references (found $rustHitCount files)" -AC 'AC-1'

# Check UI TypeScript source
$tsHits = Search-InFiles -Pattern '\bcopilot\b|\bclaude\b' -Extensions @('.ts', '.tsx') -Directory $uiSrcDir -ExcludeDirs @('node_modules')
$tsHitCount = ($tsHits | Measure-Object).Count
$tsHitDetail = if ($tsHitCount -gt 0) { ($tsHits | ForEach-Object { $_.File }) -join '; ' } else { 'none' }
Assert-True -Condition ($tsHitCount -eq 0) -Message "UI source has no copilot/claude references (found $tsHitCount files: $tsHitDetail)" -AC 'AC-1' -Evidence $tsHitDetail

# Check JSON config files (not tokenizer model files)
$jsonHits = Search-InFiles -Pattern '\bcopilot\b|\bclaude\b' -Extensions @('.json') -Directory (Join-Path $RepoRoot 'apps') -ExcludeDirs @('models', 'node_modules', 'dist', 'target')
$jsonHitCount = ($jsonHits | Measure-Object).Count
$jsonHitDetail = if ($jsonHitCount -gt 0) { ($jsonHits | ForEach-Object { $_.File }) -join '; ' } else { 'none' }
Assert-True -Condition ($jsonHitCount -eq 0) -Message "App JSON files have no copilot/claude references (found $jsonHitCount files: $jsonHitDetail)" -AC 'AC-1' -Evidence $jsonHitDetail

# ── AC-5: SetupWizard single OpenCode flow ─────────────────────────────────

Write-Host ""
Write-Host "--- AC-5: SetupWizard single OpenCode flow ---" -ForegroundColor Yellow

$setupWizardPath = Join-Path $uiSrcDir 'features\setup\components\SetupWizard.tsx'
$setupWizardContent = Get-Content $setupWizardPath -Raw

$hasProviderSelection = $setupWizardContent -match 'provider.*select|selectProvider|chooseProvider|providerCard|ProviderCard'
Assert-True -Condition (-not $hasProviderSelection) -Message "SetupWizard has no provider selection UI" -AC 'AC-5'

$hasOpenCode = $setupWizardContent -match 'OpenCode|opencode'
Assert-True -Condition $hasOpenCode -Message "SetupWizard references OpenCode" -AC 'AC-5'

$hasOldRefs = $setupWizardContent -match '\bcopilot\b|\bclaude\b'
Assert-True -Condition (-not $hasOldRefs) -Message "SetupWizard has no copilot/claude references" -AC 'AC-5'

$hasOpencodeField = $setupWizardContent -match 'opencode.*boolean|opencode_plugin_installed'
Assert-True -Condition $hasOpencodeField -Message "SetupWizard CliCheckResult has opencode fields only" -AC 'AC-5'

# ── AC-6: RunCliPanel and RunCliSettings hardcode opencode ─────────────────

Write-Host ""
Write-Host "--- AC-6: RunCli components hardcode opencode ---" -ForegroundColor Yellow

$runCliPanelPath = Join-Path $uiSrcDir 'features\run-cli\components\RunCliPanel.tsx'
$runCliPanelContent = Get-Content $runCliPanelPath -Raw

$runCliSettingsPath = Join-Path $uiSrcDir 'features\run-cli\components\RunCliSettings.tsx'
$runCliSettingsContent = Get-Content $runCliSettingsPath -Raw

Assert-True -Condition (-not ($runCliPanelContent -match 'provider.*toggle|toggleProvider|providerSelect')) -Message "RunCliPanel has no provider toggle" -AC 'AC-6'
Assert-True -Condition ($runCliPanelContent -match 'opencode|OpenCode') -Message "RunCliPanel references OpenCode" -AC 'AC-6'
Assert-True -Condition (-not ($runCliPanelContent -match '\bcopilot\b|\bclaude\b')) -Message "RunCliPanel has no copilot/claude references" -AC 'AC-6'
Assert-True -Condition (-not ($runCliSettingsContent -match 'provider.*toggle|toggleProvider|providerSelect')) -Message "RunCliSettings has no provider toggle" -AC 'AC-6'
Assert-True -Condition (-not ($runCliSettingsContent -match '\bcopilot\b|\bclaude\b')) -Message "RunCliSettings has no copilot/claude references" -AC 'AC-6'

# ── AC-7: OTLP receiver comments reference OpenCode ────────────────────────

Write-Host ""
Write-Host "--- AC-7: OTLP comments reference OpenCode ---" -ForegroundColor Yellow

$otlpDir = Join-Path $rustSrcDir 'infrastructure\otlp'
$otlpFiles = @('mod.rs', 'grpc.rs', 'http.rs', 'mapping.rs')

foreach ($otlpFile in $otlpFiles) {
  $filePath = Join-Path $otlpDir $otlpFile
  if (Test-Path $filePath) {
    $content = Get-Content $filePath -Raw
    $hasOC = $content -match 'OpenCode|opencode'
    Assert-True -Condition $hasOC -Message "OTLP ${otlpFile} references OpenCode" -AC 'AC-7'
    $hasOld = $content -match '\bcopilot\b|\bclaude\b'
    Assert-True -Condition (-not $hasOld) -Message "OTLP ${otlpFile} has no copilot/claude references" -AC 'AC-7'
  } else {
    Assert-True -Condition $false -Message "OTLP ${otlpFile} not found" -AC 'AC-7'
  }
}

# ── AC-10: Documentation references OpenCode ────────────────────────────────

Write-Host ""
Write-Host "--- AC-10: Documentation references OpenCode ---" -ForegroundColor Yellow

$docFiles = @(
  'ARCHITECTURE.md',
  'FAQ.md',
  'SCOPE.md',
  'REQUIREMENTS.md',
  'PROJECT_GOALS.md',
  'FOLDER_STRUCTURE.md',
  'tauri\ARCHITECTURE.md',
  'tauri\SETUP.md',
  'tauri\CLI_GUIDE.md'
)

foreach ($docFile in $docFiles) {
  $docPath = Join-Path $docsDir $docFile
  if (Test-Path $docPath) {
    $content = Get-Content $docPath -Raw

    $hasOC = $content -match 'OpenCode|opencode'
    Assert-True -Condition $hasOC -Message "Doc ${docFile} references OpenCode" -AC 'AC-10'

    $hasOld = $content -match '\bcopilot\b|\bclaude\b'
    if ($hasOld) {
      $evidence = "Contains copilot/claude references"
      Assert-True -Condition $false -Message "Doc ${docFile} still has copilot/claude references" -AC 'AC-10' -Evidence $evidence
    } else {
      Assert-True -Condition $true -Message "Doc ${docFile} has no copilot/claude references" -AC 'AC-10'
    }
  } else {
    Assert-True -Condition $false -Message "Doc ${docFile} not found" -AC 'AC-10'
  }
}

# ── AC-11: claude-hooks.json deleted, fredo-plugin.ts exists ───────────────

Write-Host ""
Write-Host "--- AC-11: File existence checks ---" -ForegroundColor Yellow

$claudeHooksPath = Join-Path $marketplaceDir 'claude-hooks.json'
Assert-True -Condition (-not (Test-Path $claudeHooksPath)) -Message "claude-hooks.json is deleted" -AC 'AC-11'

$allClaudeHooks = Get-ChildItem -LiteralPath $RepoRoot -Recurse -Filter 'claude-hooks.json' -ErrorAction SilentlyContinue |
  Where-Object { $_.FullName -notmatch 'node_modules|\.git|target' }
$allClaudeHooksCount = ($allClaudeHooks | Measure-Object).Count
Assert-True -Condition ($allClaudeHooksCount -eq 0) -Message "No claude-hooks.json anywhere in repo (found $allClaudeHooksCount)" -AC 'AC-11'

$fredoPluginPath = Join-Path $marketplaceDir 'fredo-plugin.ts'
Assert-True -Condition (Test-Path $fredoPluginPath) -Message "fredo-plugin.ts exists in marketplace-plugin" -AC 'AC-11'

$pluginContent = Get-Content $fredoPluginPath -Raw
Assert-True -Condition ($pluginContent -match 'OpenCode|opencode') -Message "fredo-plugin.ts references OpenCode" -AC 'AC-11'
Assert-True -Condition (-not ($pluginContent -match '\bcopilot\b|\bclaude\b')) -Message "fredo-plugin.ts has no copilot/claude references" -AC 'AC-11'

# ── AC-12: pnpm-workspace.yaml references marketplace-plugin, not copilot ──

Write-Host ""
Write-Host "--- AC-12: Workspace config ---" -ForegroundColor Yellow

$workspacePath = Join-Path $RepoRoot 'pnpm-workspace.yaml'
$workspaceContent = Get-Content $workspacePath -Raw

Assert-True -Condition ($workspaceContent -match 'marketplace-plugin') -Message "pnpm-workspace.yaml references marketplace-plugin" -AC 'AC-12'
Assert-True -Condition (-not ($workspaceContent -match 'copilot-plugin')) -Message "pnpm-workspace.yaml does not reference copilot-plugin" -AC 'AC-12'

$copilotPluginDir = Join-Path $RepoRoot 'apps\copilot-plugin'
Assert-True -Condition (-not (Test-Path $copilotPluginDir)) -Message "apps/copilot-plugin directory does not exist" -AC 'AC-12'

# ── AC-8: EventSource enum casing consistency ──────────────────────────────

Write-Host ""
Write-Host "--- AC-8: EventSource enum casing consistency ---" -ForegroundColor Yellow

$eventSourceCheckFiles = @(
  @{ Name = 'DevMode.tsx'; Path = (Join-Path $uiSrcDir 'features\dev-mode\components\DevMode.tsx') },
  @{ Name = 'useDevModeStream.ts'; Path = (Join-Path $uiSrcDir 'features\dev-mode\hooks\useDevModeStream.ts') },
  @{ Name = 'SpatiotemporalManifold.tsx'; Path = (Join-Path $uiSrcDir 'features\dev-mode\components\SpatiotemporalManifold.tsx') }
)

# The correct EventSource values (matching Rust serde camelCase) are:
# 'hook', 'otlpGrpc', 'otlpHttp'
# Wrong PascalCase values that would break at runtime:
# 'Hook', 'OtlpGrpc', 'OtlpHttp'

foreach ($fileInfo in $eventSourceCheckFiles) {
  if (Test-Path $fileInfo.Path) {
    $content = Get-Content $fileInfo.Path -Raw

    # Check for PascalCase EventSource string literals
    $hasHookPascal = $content -match "'Hook'"
    $hasOtlpGrpcPascal = $content -match "'OtlpGrpc'"
    $hasOtlpHttpPascal = $content -match "'OtlpHttp'"

    $wrongCount = 0
    if ($hasHookPascal) { $wrongCount++ }
    if ($hasOtlpGrpcPascal) { $wrongCount++ }
    if ($hasOtlpHttpPascal) { $wrongCount++ }

    if ($wrongCount -gt 0) {
      Assert-True -Condition $false -Message "$($fileInfo.Name) uses PascalCase EventSource values ($wrongCount instances - should be camelCase: 'hook', 'otlpGrpc', 'otlpHttp')" -AC 'AC-8' -Evidence "PascalCase EventSource references break type safety"
    } else {
      Assert-True -Condition $true -Message "$($fileInfo.Name) uses correct camelCase EventSource values" -AC 'AC-8'
    }
  } else {
    Assert-True -Condition $false -Message "$($fileInfo.Name) not found" -AC 'AC-8'
  }
}

# ── AC-9: Rust EventSource enum correctness ────────────────────────────────

Write-Host ""
Write-Host "--- AC-9: Rust EventSource and backend checks ---" -ForegroundColor Yellow

$eventsModPath = Join-Path $rustSrcDir 'infrastructure\events\mod.rs'
$eventsContent = Get-Content $eventsModPath -Raw

$eventSourceOtlpBlock = [regex]::Match($eventsContent, 'OtlpGrpc[^}]*OtlpHttp[^}]*\}', [System.Text.RegularExpressions.RegexOptions]::Singleline).Value
$otlpBlockHasOpenCode = $eventSourceOtlpBlock -match 'OpenCode'
Assert-True -Condition $otlpBlockHasOpenCode -Message "EventSource OTLP variants reference OpenCode" -AC 'AC-9'
Assert-True -Condition (-not ($eventsContent -match '\bcopilot\b|\bclaude\b')) -Message "events/mod.rs has no copilot/claude references" -AC 'AC-9'

# ── AC-2/3/4: Rust setup commands ──────────────────────────────────────────

Write-Host ""
Write-Host "--- AC-2/3/4: Rust setup commands ---" -ForegroundColor Yellow

$setupCommandsPath = Join-Path $rustSrcDir 'features\setup\commands.rs'
$setupContent = Get-Content $setupCommandsPath -Raw

Assert-True -Condition (-not ($setupContent -match '\bcopilot\b.*bool|\bclaude\b.*bool')) -Message "setup/commands.rs has no copilot/claude fields in CliCheckResult" -AC 'AC-2'
Assert-True -Condition ($setupContent -match 'opencode.*bool|opencode_plugin_installed') -Message "setup/commands.rs has opencode fields in CliCheckResult" -AC 'AC-2'
Assert-True -Condition ($setupContent -match 'configure_opencode_otel') -Message "setup/commands.rs has configure_opencode_otel function" -AC 'AC-3'
Assert-True -Condition (-not ($setupContent -match 'configure_otel.*provider|provider.*configure_otel')) -Message "setup/commands.rs has no provider parameter in configure_otel" -AC 'AC-3'
Assert-True -Condition ($setupContent -match 'install_plugin') -Message "setup/commands.rs has install_plugin function" -AC 'AC-4'

# ── AC-6 (backend): Terminal commands ──────────────────────────────────────

Write-Host ""
Write-Host "--- AC-6 (backend): Terminal commands ---" -ForegroundColor Yellow

$terminalCommandsPath = Join-Path $rustSrcDir 'features\terminal\commands.rs'
$terminalContent = Get-Content $terminalCommandsPath -Raw

Assert-True -Condition ($terminalContent -match '"opencode"') -Message "terminal/commands.rs resolves opencode binary" -AC 'AC-6'
Assert-True -Condition (-not ($terminalContent -match '\bcopilot\b|\bclaude\b')) -Message "terminal/commands.rs has no copilot/claude references" -AC 'AC-6'

# ── Summary ─────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Test Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Passed: $script:passed" -ForegroundColor Green
Write-Host "  Failed: $script:failed" -ForegroundColor Red
Write-Host "  Total:  $($script:passed + $script:failed)" -ForegroundColor Cyan

if ($script:failed -gt 0) {
  Write-Host ""
  Write-Host "Failed tests:" -ForegroundColor Red
  foreach ($r in $script:results) {
    if ($r.Status -eq 'FAIL') {
      Write-Host "  [$($r.AC)] $($r.Message)" -ForegroundColor Red
      if ($r.Evidence) { Write-Host "    Evidence: $($r.Evidence)" -ForegroundColor DarkGray }
    }
  }
}

Write-Host ""
exit $(if ($script:failed -gt 0) { 1 } else { 0 })
