# E2E verification tests for Phase 2: CLI Simplification (Spec #17)
# Verifies AC-2.1 through AC-2.5
# Generated by @fredo-tester

param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..'))
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:passed = 0
$script:failed = 0
$script:results = @()

function Assert-True {
  param([bool]$Condition, [string]$Message, [string]$AC = '', [string]$Evidence = '')
  if ($Condition) {
    $script:passed++
    $script:results += @{ AC = $AC; Status = 'PASS'; Message = $Message; Evidence = $Evidence }
    Write-Host "  PASS: $Message" -ForegroundColor Green
  } else {
    $script:failed++
    $script:results += @{ AC = $AC; Status = 'FAIL'; Message = $Message; Evidence = $Evidence }
    Write-Host "  FAIL: $Message" -ForegroundColor Red
  }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Phase 2: CLI Simplification Verification" -ForegroundColor Cyan
Write-Host " Spec: #17  |  PR: #23" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ── AC-2.1: fredo hook returns clap error ─────────────────────────────────────

Write-Host "--- AC-2.1: 'fredo hook' returns error (unknown command) ---" -ForegroundColor Yellow

$cliModPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\src\infrastructure\cli\mod.rs'
$cliContent = Get-Content $cliModPath -Raw

# Verify hook is NOT in the Commands enum
Assert-True -Condition (-not ($cliContent -match 'Commands::Hook\b')) -Message "CLI mod.rs does not have Commands::Hook" -AC 'AC-2.1'
Assert-True -Condition (-not ($cliContent -match 'hook\b.*subcommand|subcommand.*hook')) -Message "CLI mod.rs has no Hook subcommand" -AC 'AC-2.1'

# Verify hook.rs is deleted
$hookRsPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\src\infrastructure\cli\commands\hook.rs'
Assert-True -Condition (-not (Test-Path $hookRsPath)) -Message "hook.rs is deleted" -AC 'AC-2.1'

# Verify mod.rs no longer exports hook
$commandsModPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\src\infrastructure\cli\commands\mod.rs'
$commandsContent = Get-Content $commandsModPath -Raw
Assert-True -Condition (-not ($commandsContent -match 'pub mod hook')) -Message "commands/mod.rs does not export hook module" -AC 'AC-2.1'

# ── AC-2.2: fredo mcp returns clap error ──────────────────────────────────────

Write-Host ""
Write-Host "--- AC-2.2: 'fredo mcp' returns error (unknown command) ---" -ForegroundColor Yellow

# Verify mcp is NOT in the Commands enum
Assert-True -Condition (-not ($cliContent -match 'Commands::Mcp\b')) -Message "CLI mod.rs does not have Commands::Mcp" -AC 'AC-2.2'
Assert-True -Condition (-not ($cliContent -match 'McpArgs|subcommand.*mcp|mcp.*subcommand')) -Message "CLI mod.rs has no Mcp subcommand or McpArgs" -AC 'AC-2.2'

# ── AC-2.3: fredo opencode-plugin --help shows usage ──────────────────────────

Write-Host ""
Write-Host "--- AC-2.3: opencode-plugin subcommand is defined correctly ---" -ForegroundColor Yellow

$opencodePluginRsPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\src\infrastructure\cli\commands\opencode_plugin.rs'
Assert-True -Condition (Test-Path $opencodePluginRsPath) -Message "opencode_plugin.rs exists" -AC 'AC-2.3'

$opencodePluginContent = Get-Content $opencodePluginRsPath -Raw

# Check for OpenCodePluginArgs struct with event_type positional arg and --payload flag
Assert-True -Condition ($opencodePluginContent -match 'OpenCodePluginArgs') -Message "OpenCodePluginArgs struct exists" -AC 'AC-2.3'
Assert-True -Condition ($opencodePluginContent -match 'pub event_type:') -Message "OpenCodePluginArgs has event_type positional arg" -AC 'AC-2.3'
Assert-True -Condition ($opencodePluginContent -match '#\[arg\(short, long\)\]') -Message "OpenCodePluginArgs has --payload flag" -AC 'AC-2.3'

# Verify CLI mod.rs has OpenCodePlugin command
Assert-True -Condition ($cliContent -match 'Commands::OpenCodePlugin') -Message "CLI mod.rs has Commands::OpenCodePlugin" -AC 'AC-2.3'
Assert-True -Condition ($cliContent -match 'OpenCodePlugin\(OpenCodePluginArgs\)') -Message "CLI mod.rs maps OpenCodePlugin to OpenCodePluginArgs" -AC 'AC-2.3'

# Verify --help would show opencode-plugin
Assert-True -Condition ($cliContent -match "opencode-plugin" -or $cliContent -match "OpenCode plugin") -Message "CLI help text references opencode-plugin" -AC 'AC-2.3'

# ── AC-2.4: opencode_plugin.rs file exists with OpenCodePluginArgs ────────────

Write-Host ""
Write-Host "--- AC-2.4: opencode_plugin.rs exists with OpenCodePluginArgs ---" -ForegroundColor Yellow

# Already verified above, but let's be explicit
Assert-True -Condition (Test-Path $opencodePluginRsPath) -Message "opencode_plugin.rs file exists" -AC 'AC-2.4'
Assert-True -Condition ($opencodePluginContent -match 'pub struct OpenCodePluginArgs') -Message "OpenCodePluginArgs struct is defined" -AC 'AC-2.4'
Assert-True -Condition ($opencodePluginContent -match 'use clap::Args') -Message "OpenCodePluginArgs derives Args from clap" -AC 'AC-2.4'

# Verify it's exported from commands/mod.rs
Assert-True -Condition ($commandsContent -match 'pub mod opencode_plugin') -Message "commands/mod.rs exports opencode_plugin module" -AC 'AC-2.4'

# ── AC-2.5: cargo build succeeds (source-level checks) ────────────────────────

Write-Host ""
Write-Host "--- AC-2.5: CLI infrastructure compiles cleanly ---" -ForegroundColor Yellow

# Verify the IPC module compiles: CliCommand::OpenCodePlugin exists
$ipcPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\src\infrastructure\ipc.rs'
$ipcContent = Get-Content $ipcPath -Raw

Assert-True -Condition ($ipcContent -match 'CliCommand::OpenCodePlugin') -Message "ipc.rs has CliCommand::OpenCodePlugin variant" -AC 'AC-2.5'
Assert-True -Condition (-not ($ipcContent -match 'CliCommand::AgentHook')) -Message "ipc.rs does NOT have CliCommand::AgentHook (renamed)" -AC 'AC-2.5'

# Verify dispatch function exists for OpenCodePlugin
Assert-True -Condition ($ipcContent -match 'dispatch_opencode_plugin') -Message "ipc.rs has dispatch_opencode_plugin function" -AC 'AC-2.5'
Assert-True -Condition (-not ($ipcContent -match 'dispatch_agent_hook')) -Message "ipc.rs does NOT have dispatch_agent_hook (renamed)" -AC 'AC-2.5'

# Verify mcp module no longer has CliCapable/McpCapable
$mcpModPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\src\features\mcp\mod.rs'
$mcpContent = Get-Content $mcpModPath -Raw

Assert-True -Condition (-not ($mcpContent -match 'CliCapable')) -Message "mcp/mod.rs does not implement CliCapable" -AC 'AC-2.5'
Assert-True -Condition (-not ($mcpContent -match 'McpCapable')) -Message "mcp/mod.rs does not implement McpCapable" -AC 'AC-2.5'

# Verify capability.rs no longer has McpCapable trait
$capPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\src\runtime\capability.rs'
$capContent = Get-Content $capPath -Raw

Assert-True -Condition (-not ($capContent -match 'trait McpCapable')) -Message "capability.rs does not define McpCapable trait" -AC 'AC-2.5'
Assert-True -Condition ($capContent -match 'trait CliCapable') -Message "capability.rs still defines CliCapable trait" -AC 'AC-2.5'

# Verify CLI dispatch references OpenCodePlugin (not Hook)
Assert-True -Condition ($cliContent -match 'OpenCodePlugin') -Message "CLI mod.rs references OpenCodePlugin in dispatch" -AC 'AC-2.5'
Assert-True -Condition (-not ($cliContent -match 'Commands::Hook\b')) -Message "CLI mod.rs does NOT reference Commands::Hook" -AC 'AC-2.5'

# ── Summary ────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Phase 2 Test Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Passed: $script:passed" -ForegroundColor Green
Write-Host "  Failed: $script:failed" -ForegroundColor Red
Write-Host "  Total:  $($script:passed + $script:failed)" -ForegroundColor Cyan

if ($script:failed -gt 0) {
  Write-Host ""
  Write-Host "Failed tests:" -ForegroundColor Red
  foreach ($r in $script:results) {
    if ($r.Status -eq 'FAIL') {
      Write-Host "  [$($r.AC)] $($r.Message)" -ForegroundColor Red
      if ($r.Evidence) { Write-Host "    Evidence: $($r.Evidence)" -ForegroundColor DarkGray }
    }
  }
}

Write-Host ""
exit $(if ($script:failed -gt 0) { 1 } else { 0 })