# E2E verification tests for Phase 1: Brand Cleanup (Spec #17)
# Verifies AC-1.1 through AC-1.5
# Generated by @fredo-tester

param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..'))
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:passed = 0
$script:failed = 0
$script:results = @()

function Assert-True {
  param([bool]$Condition, [string]$Message, [string]$AC = '', [string]$Evidence = '')
  if ($Condition) {
    $script:passed++
    $script:results += @{ AC = $AC; Status = 'PASS'; Message = $Message; Evidence = $Evidence }
    Write-Host "  PASS: $Message" -ForegroundColor Green
  } else {
    $script:failed++
    $script:results += @{ AC = $AC; Status = 'FAIL'; Message = $Message; Evidence = $Evidence }
    Write-Host "  FAIL: $Message" -ForegroundColor Red
  }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Phase 1: Brand Cleanup Verification" -ForegroundColor Cyan
Write-Host " Spec: #17  |  PR: #23" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ── AC-1.1: Asset files renamed from fredo to fredo ──────────────────────────

Write-Host "--- AC-1.1: Asset files renamed from fredo to fredo ---" -ForegroundColor Yellow

$assetsDir = Join-Path $RepoRoot 'apps\ui\src\assets'

# Check fredo files exist
$fredoFiles = @('fredo.png', 'fredo-logo.png', 'fredo-logo-trimmed.png', 'fredo-logo-icon.png')
foreach ($f in $fredoFiles) {
  $path = Join-Path $assetsDir $f
  Assert-True -Condition (Test-Path $path) -Message "Asset exists: $f" -AC 'AC-1.1' -Evidence $path
}

# Check NO fredo files remain
$fredoFiles = Get-ChildItem -LiteralPath $assetsDir -Filter 'fredo*' -ErrorAction SilentlyContinue
$fredoCount = ($fredoFiles | Measure-Object).Count
Assert-True -Condition ($fredoCount -eq 0) -Message "No fredo-*.png files remain in assets (found $fredoCount)" -AC 'AC-1.1'

# ── AC-1.2: DesktopToolbar imports fredo-logo-icon.png ────────────────────────

Write-Host ""
Write-Host "--- AC-1.2: DesktopToolbar imports fredo-logo-icon.png ---" -ForegroundColor Yellow

$desktopToolbarPath = Join-Path $RepoRoot 'apps\ui\src\features\home\components\settings\DesktopToolbar.tsx'
$desktopToolbarContent = Get-Content $desktopToolbarPath -Raw

Assert-True -Condition ($desktopToolbarContent -match 'fredo-logo-icon') -Message "DesktopToolbar imports fredo-logo-icon" -AC 'AC-1.2'
Assert-True -Condition (-not ($desktopToolbarContent -match 'fredo-logo-icon')) -Message "DesktopToolbar does NOT import fredo-logo-icon" -AC 'AC-1.2'

# ── AC-1.3: code-sandbox package.json branding ───────────────────────────────

Write-Host ""
Write-Host "--- AC-1.3: code-sandbox package.json branding ---" -ForegroundColor Yellow

$codeSandboxPkgPath = Join-Path $RepoRoot 'apps\code-sandbox\package.json'
$codeSandboxPkg = Get-Content $codeSandboxPkgPath -Raw | ConvertFrom-Json

Assert-True -Condition ($codeSandboxPkg.name -eq '@fredo/code-sandbox') -Message "Package name is @fredo/code-sandbox (actual: $($codeSandboxPkg.name))" -AC 'AC-1.3'
Assert-True -Condition ($codeSandboxPkg.description -match 'Fredo') -Message "Description contains 'Fredo' (actual: $($codeSandboxPkg.description))" -AC 'AC-1.3'

# ── AC-1.4: code-sandbox/src/index.ts has no Fredo/fredo references ──────────

Write-Host ""
Write-Host "--- AC-1.4: code-sandbox index.ts no Fredo references ---" -ForegroundColor Yellow

$indexTsPath = Join-Path $RepoRoot 'apps\code-sandbox\src\index.ts'
$indexTsContent = Get-Content $indexTsPath -Raw

# Check for Fredo or fredo (case-insensitive), excluding "Fredosian"
$fredoMatches = [regex]::Matches($indexTsContent, '(?i)\bfredo\b')
$fredoHits = @()
foreach ($m in $fredoMatches) {
  $word = $m.Value
  $fredoHits += $word
}

# Filter out "Fredosian" hits manually — the regex matches "Fredo" inside "Fredosian" 
# but we should check the context: if the match is part of "Fredosian", exclude it
$realFredoHits = @()
$fredoCaseMatches = [regex]::Matches($indexTsContent, '(?i)fredo(?!sian)') 
$realFredoCount = $fredoCaseMatches.Count

Assert-True -Condition ($realFredoCount -eq 0) -Message "index.ts has no Fredo/fredo references excluding Fredosian (found $realFredoCount)" -AC 'AC-1.4'

# ── AC-1.5: CodeExecuteTool.ts no Fredo/fredo (excluding Fredosian) + fredo socket paths ─

Write-Host ""
Write-Host "--- AC-1.5: CodeExecuteTool.ts no Fredo refs + fredo socket paths ---" -ForegroundColor Yellow

$codeExecuteToolPath = Join-Path $RepoRoot 'apps\code-sandbox\src\tools\code_execute\CodeExecuteTool.ts'
$codeExecuteToolContent = Get-Content $codeExecuteToolPath -Raw

# Check for Fredo/fredo excluding "Fredosian"
$fredoCaseMatches2 = [regex]::Matches($codeExecuteToolContent, '(?i)fredo(?!sian)')
$realFredoCount2 = $fredoCaseMatches2.Count
Assert-True -Condition ($realFredoCount2 -eq 0) -Message "CodeExecuteTool.ts has no Fredo/fredo references excluding Fredosian (found $realFredoCount2)" -AC 'AC-1.5'

# Check socket paths use /var/run/fredo/ not /var/run/fredo/
$hasFredoSocket = $codeExecuteToolContent -match '/var/run/fredo/'
Assert-True -Condition $hasFredoSocket -Message "CodeExecuteTool.ts uses /var/run/fredo/ socket path" -AC 'AC-1.5'

$hasFredoSocket = $codeExecuteToolContent -match '/var/run/fredo/'
Assert-True -Condition (-not $hasFredoSocket) -Message "CodeExecuteTool.ts does NOT use /var/run/fredo/ socket path" -AC 'AC-1.5'

# Check doc.md as well
$docMdPath = Join-Path $RepoRoot 'apps\code-sandbox\src\tools\code_execute\doc.md'
if (Test-Path $docMdPath) {
  $docMdContent = Get-Content $docMdPath -Raw
  $docMdFredoMatches = [regex]::Matches($docMdContent, '(?i)fredo(?!sian)')
  $docMdFredoCount = $docMdFredoMatches.Count
  Assert-True -Condition ($docMdFredoCount -eq 0) -Message "doc.md has no Fredo/fredo references excluding Fredosian (found $docMdFredoCount)" -AC 'AC-1.5'
  $docMdFredoPath = $docMdContent -match '/var/run/fredo/'
  Assert-True -Condition $docMdFredoPath -Message "doc.md uses /var/run/fredo/ socket path" -AC 'AC-1.5'
}

# ── Bonus: Check marketplace-plugin is deleted ─────────────────────────────────

Write-Host ""
Write-Host "--- Bonus: marketplace-plugin directory deleted ---" -ForegroundColor Yellow

$marketplaceDir = Join-Path $RepoRoot 'apps\marketplace-plugin'
Assert-True -Condition (-not (Test-Path $marketplaceDir)) -Message "apps/marketplace-plugin directory is deleted" -AC 'Bonus'

# ── Summary ────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Phase 1 Test Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Passed: $script:passed" -ForegroundColor Green
Write-Host "  Failed: $script:failed" -ForegroundColor Red
Write-Host "  Total:  $($script:passed + $script:failed)" -ForegroundColor Cyan

if ($script:failed -gt 0) {
  Write-Host ""
  Write-Host "Failed tests:" -ForegroundColor Red
  foreach ($r in $script:results) {
    if ($r.Status -eq 'FAIL') {
      Write-Host "  [$($r.AC)] $($r.Message)" -ForegroundColor Red
      if ($r.Evidence) { Write-Host "    Evidence: $($r.Evidence)" -ForegroundColor DarkGray }
    }
  }
}

Write-Host ""
exit $(if ($script:failed -gt 0) { 1 } else { 0 })