# E2E verification tests for Phase 3: OpenCode Plugin + Security (Spec #17)
# Verifies AC-3.1 through AC-3.11 and SEC-REQ-1 through SEC-REQ-4
# Generated by @fredo-tester

param(
  [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..'))
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$script:passed = 0
$script:failed = 0
$script:results = @()

function Assert-True {
  param([bool]$Condition, [string]$Message, [string]$AC = '', [string]$Evidence = '')
  if ($Condition) {
    $script:passed++
    $script:results += @{ AC = $AC; Status = 'PASS'; Message = $Message; Evidence = $Evidence }
    Write-Host "  PASS: $Message" -ForegroundColor Green
  } else {
    $script:failed++
    $script:results += @{ AC = $AC; Status = 'FAIL'; Message = $Message; Evidence = $Evidence }
    Write-Host "  FAIL: $Message" -ForegroundColor Red
  }
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Phase 3: OpenCode Plugin + Security" -ForegroundColor Cyan
Write-Host " Spec: #17  |  PR: #23" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# ── AC-3.1: Plugin exports default function with typed hooks ──────────────────

Write-Host "--- AC-3.1: Plugin exports default function with typed hooks ---" -ForegroundColor Yellow

$pluginIndexPath = Join-Path $RepoRoot 'apps\opencode-plugin\src\index.ts'
Assert-True -Condition (Test-Path $pluginIndexPath) -Message "apps/opencode-plugin/src/index.ts exists" -AC 'AC-3.1'

$pluginContent = Get-Content $pluginIndexPath -Raw

# Check for default export of Plugin function
Assert-True -Condition ($pluginContent -match 'export default function Plugin') -Message "Plugin exports default function named Plugin" -AC 'AC-3.1'

# Check for Plugin type import from @opencode-ai/plugin
Assert-True -Condition ($pluginContent -match "import.*Plugin.*from '@opencode-ai/plugin'") -Message "Plugin imports Plugin type from @opencode-ai/plugin" -AC 'AC-3.1'

# Check for ctx.on() hook registration
Assert-True -Condition ($pluginContent -match 'ctx\.on\(') -Message "Plugin registers hooks via ctx.on()" -AC 'AC-3.1'

# ── AC-3.2: chat.message hook ─────────────────────────────────────────────────

Write-Host ""
Write-Host "--- AC-3.2: chat.message hook forwards via opencode-plugin CLI ---" -ForegroundColor Yellow

Assert-True -Condition ($pluginContent -match "'chat\.message'") -Message "Plugin registers chat.message hook" -AC 'AC-3.2'
Assert-True -Condition ($pluginContent -match "forwardEvent\(ctx, 'chat\.message'") -Message "chat.message hook calls forwardEvent with 'chat.message'" -AC 'AC-3.2'

# ── AC-3.3: tool.execute.before hook ──────────────────────────────────────────

Write-Host ""
Write-Host "--- AC-3.3: tool.execute.before hook ---" -ForegroundColor Yellow

Assert-True -Condition ($pluginContent -match "'tool\.execute\.before'") -Message "Plugin registers tool.execute.before hook" -AC 'AC-3.3'
Assert-True -Condition ($pluginContent -match "forwardEvent\(ctx, 'tool\.execute\.before'") -Message "tool.execute.before hook calls forwardEvent" -AC 'AC-3.3'

# ── AC-3.4: tool.execute.after hook ────────────────────────────────────────────

Write-Host ""
Write-Host "--- AC-3.4: tool.execute.after hook ---" -ForegroundColor Yellow

Assert-True -Condition ($pluginContent -match "'tool\.execute\.after'") -Message "Plugin registers tool.execute.after hook" -AC 'AC-3.4'
Assert-True -Condition ($pluginContent -match "forwardEvent\(ctx, 'tool\.execute\.after'") -Message "tool.execute.after hook calls forwardEvent" -AC 'AC-3.4'

# ── AC-3.5: permission.ask hook ──────────────────────────────────────────────

Write-Host ""
Write-Host "--- AC-3.5: permission.ask hook ---" -ForegroundColor Yellow

Assert-True -Condition ($pluginContent -match "'permission\.ask'") -Message "Plugin registers permission.ask hook" -AC 'AC-3.5'
Assert-True -Condition ($pluginContent -match "forwardEvent\(ctx, 'permission\.ask'") -Message "permission.ask hook calls forwardEvent" -AC 'AC-3.5'

# ── AC-3.6: command.execute.before hook ────────────────────────────────────────

Write-Host ""
Write-Host "--- AC-3.6: command.execute.before hook ---" -ForegroundColor Yellow

Assert-True -Condition ($pluginContent -match "'command\.execute\.before'") -Message "Plugin registers command.execute.before hook" -AC 'AC-3.6'
Assert-True -Condition ($pluginContent -match "forwardEvent\(ctx, 'command\.execute\.before'") -Message "command.execute.before hook calls forwardEvent" -AC 'AC-3.6'

# ── AC-3.7: shell.env hook ────────────────────────────────────────────────────

Write-Host ""
Write-Host "--- AC-3.7: shell.env hook ---" -ForegroundColor Yellow

Assert-True -Condition ($pluginContent -match "'shell\.env'") -Message "Plugin registers shell.env hook" -AC 'AC-3.7'
Assert-True -Condition ($pluginContent -match "forwardEvent\(ctx, 'shell\.env'") -Message "shell.env hook calls forwardEvent" -AC 'AC-3.7'

# ── AC-3.8: event (catch-all) hook ────────────────────────────────────────────

Write-Host ""
Write-Host "--- AC-3.8: event (catch-all) hook ---" -ForegroundColor Yellow

Assert-True -Condition ($pluginContent -match "'event'") -Message "Plugin registers event hook" -AC 'AC-3.8'
Assert-True -Condition ($pluginContent -match "forwardEvent\(ctx, 'event'") -Message "event hook calls forwardEvent" -AC 'AC-3.8'

# ── AC-3.9: Setup commands reference opencode-plugin ─────────────────────────

Write-Host ""
Write-Host "--- AC-3.9: Setup commands reference opencode-plugin ---" -ForegroundColor Yellow

$setupCommandsPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\src\features\setup\commands.rs'
$setupContent = Get-Content $setupCommandsPath -Raw

Assert-True -Condition ($setupContent -match 'apps/opencode-plugin') -Message "setup/commands.rs references apps/opencode-plugin" -AC 'AC-3.9'
Assert-True -Condition (-not ($setupContent -match 'apps/marketplace-plugin')) -Message "setup/commands.rs does NOT reference apps/marketplace-plugin" -AC 'AC-3.9'

# ── AC-3.10: tauri.conf.json references opencode-plugin/plugin.json ───────────

Write-Host ""
Write-Host "--- AC-3.10: tauri.conf.json references opencode-plugin ---" -ForegroundColor Yellow

$tauriConfPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\tauri.conf.json'
$tauriConfContent = Get-Content $tauriConfPath -Raw

Assert-True -Condition ($tauriConfContent -match 'apps/opencode-plugin/plugin\.json') -Message "tauri.conf.json references apps/opencode-plugin/plugin.json" -AC 'AC-3.10'
Assert-True -Condition (-not ($tauriConfContent -match 'apps/marketplace-plugin')) -Message "tauri.conf.json does NOT reference apps/marketplace-plugin" -AC 'AC-3.10'

# ── AC-3.11: pnpm-workspace.yaml lists opencode-plugin ────────────────────────

Write-Host ""
Write-Host "--- AC-3.11: pnpm-workspace.yaml lists opencode-plugin ---" -ForegroundColor Yellow

$workspacePath = Join-Path $RepoRoot 'pnpm-workspace.yaml'
$workspaceContent = Get-Content $workspacePath -Raw

Assert-True -Condition ($workspaceContent -match 'apps/opencode-plugin') -Message "pnpm-workspace.yaml lists apps/opencode-plugin" -AC 'AC-3.11'
Assert-True -Condition (-not ($workspaceContent -match 'apps/marketplace-plugin')) -Message "pnpm-workspace.yaml does NOT list apps/marketplace-plugin" -AC 'AC-3.11'

# ── SEC-REQ-1: ipc.rs contains 0o600 socket permission ────────────────────────

Write-Host ""
Write-Host "--- SEC-REQ-1: Socket permission restriction (0o600) ---" -ForegroundColor Yellow

$ipcPath = Join-Path $RepoRoot 'apps\tauri\src-tauri\src\infrastructure\ipc.rs'
$ipcContent = Get-Content $ipcPath -Raw

Assert-True -Condition ($ipcContent -match '0o600') -Message "ipc.rs contains 0o600 permission restriction" -AC 'SEC-REQ-1'
Assert-True -Condition ($ipcContent -match 'SEC-REQ-1|socket.*permission|restrict.*socket|owner-only') -Message "ipc.rs has comment referencing SEC-REQ-1 or socket restriction" -AC 'SEC-REQ-1'

# ── SEC-REQ-2: ipc.rs contains event type allowlist ────────────────────────────

Write-Host ""
Write-Host "--- SEC-REQ-2: Event type allowlist in ipc.rs ---" -ForegroundColor Yellow

Assert-True -Condition ($ipcContent -match 'ALLOWED_EVENT_TYPES') -Message "ipc.rs defines ALLOWED_EVENT_TYPES constant" -AC 'SEC-REQ-2'

# Verify key event types are in the allowlist
$requiredEvents = @('PreToolUse', 'PostToolUse', 'event', 'chat.message', 'permission.ask', 'tool.execute.before')
foreach ($evt in $requiredEvents) {
  Assert-True -Condition ($ipcContent -match [regex]::Escape($evt)) -Message "ALLOWED_EVENT_TYPES contains '$evt'" -AC 'SEC-REQ-2'
}

# Verify validation is applied
Assert-True -Condition ($ipcContent -match 'Unknown event type') -Message "ipc.rs returns error for unknown event types" -AC 'SEC-REQ-2'

# ── SEC-REQ-3: Plugin uses .args() method (not string interpolation) ──────────

Write-Host ""
Write-Host "--- SEC-REQ-3: Plugin uses .args() for safe CLI invocation ---" -ForegroundColor Yellow

# Check that forwardEvent uses .args() array-style invocation
Assert-True -Condition ($pluginContent -match '\.args\(') -Message "Plugin uses .args() method for CLI arguments" -AC 'SEC-REQ-3'

# Check that forwardEvent does NOT use string interpolation (template literals with ${})
# in the command itself (the payload is stringified and passed as arg, not interpolated)
$forwardEventBlock = [regex]::Match($pluginContent, 'async function forwardEvent[\s\S]*?(?=\n\n|\n// ──)').Value
$hasTemplateInterpInCmd = $forwardEventBlock -match 'ctx\.\$\`.*\$\{'
Assert-True -Condition (-not $hasTemplateInterpInCmd) -Message "forwardEvent does not use string interpolation in ctx.$ commands" -AC 'SEC-REQ-3'

# Verify the .args() pattern includes the eventType and --payload
Assert-True -Condition ($pluginContent -match '\.args\(\[eventType') -Message ".args() passes eventType as first argument" -AC 'SEC-REQ-3'
Assert-True -Condition ($pluginContent -match "'--payload'") -Message "forwardEvent passes --payload flag in args array" -AC 'SEC-REQ-3'

# Check for SEC-REQ-3 comment
Assert-True -Condition ($pluginContent -match 'SEC-REQ-3') -Message "Plugin has SEC-REQ-3 comment documenting safe arg passing" -AC 'SEC-REQ-3'

# ── SEC-REQ-4: ipc.rs contains 1MB max payload size check ────────────────────

Write-Host ""
Write-Host "--- SEC-REQ-4: Max payload size check (1MB) ---" -ForegroundColor Yellow

Assert-True -Condition ($ipcContent -match 'MAX_PAYLOAD_BYTES') -Message "ipc.rs defines MAX_PAYLOAD_BYTES constant" -AC 'SEC-REQ-4'
Assert-True -Condition ($ipcContent -match '1024 \* 1024|1_048_576') -Message "MAX_PAYLOAD_BYTES is 1MB (1024*1024)" -AC 'SEC-REQ-4'
Assert-True -Condition ($ipcContent -match 'Payload too large') -Message "ipc.rs rejects oversized payloads with error" -AC 'SEC-REQ-4'
Assert-True -Condition ($ipcContent -match 'SEC-REQ-4|max.*payload.*size|payload.*size.*limit') -Message "ipc.rs has comment referencing SEC-REQ-4 or payload size" -AC 'SEC-REQ-4'

# ── Bonus: plugin.json and package.json structure ─────────────────────────────

Write-Host ""
Write-Host "--- Bonus: Plugin package structure ---" -ForegroundColor Yellow

$pluginJsonPath = Join-Path $RepoRoot 'apps\opencode-plugin\plugin.json'
Assert-True -Condition (Test-Path $pluginJsonPath) -Message "apps/opencode-plugin/plugin.json exists" -AC 'Bonus'

$pluginJsonContent = Get-Content $pluginJsonPath -Raw | ConvertFrom-Json
Assert-True -Condition ($pluginJsonContent.name -eq 'fredo') -Message "plugin.json name is 'fredo'" -AC 'Bonus'
Assert-True -Condition ($pluginJsonContent.version -eq '3.0.0') -Message "plugin.json version is 3.0.0" -AC 'Bonus'

$pluginPkgPath = Join-Path $RepoRoot 'apps\opencode-plugin\package.json'
$pluginPkgContent = Get-Content $pluginPkgPath -Raw | ConvertFrom-Json
Assert-True -Condition ($pluginPkgContent.name -eq '@fredo/opencode-plugin') -Message "package.json name is @fredo/opencode-plugin" -AC 'Bonus'
Assert-True -Condition ($pluginPkgContent.description -match 'Fredo') -Message "package.json description contains 'Fredo'" -AC 'Bonus'

# ── Bonus: marketplace-plugin is deleted ─────────────────────────────────────────

Write-Host ""
Write-Host "--- Bonus: marketplace-plugin deleted ---" -ForegroundColor Yellow

$marketplaceDir = Join-Path $RepoRoot 'apps\marketplace-plugin'
Assert-True -Condition (-not (Test-Path $marketplaceDir)) -Message "apps/marketplace-plugin directory is deleted" -AC 'Bonus'

# ── Summary ────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Phase 3 Test Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Passed: $script:passed" -ForegroundColor Green
Write-Host "  Failed: $script:failed" -ForegroundColor Red
Write-Host "  Total:  $($script:passed + $script:failed)" -ForegroundColor Cyan

if ($script:failed -gt 0) {
  Write-Host ""
  Write-Host "Failed tests:" -ForegroundColor Red
  foreach ($r in $script:results) {
    if ($r.Status -eq 'FAIL') {
      Write-Host "  [$($r.AC)] $($r.Message)" -ForegroundColor Red
      if ($r.Evidence) { Write-Host "    Evidence: $($r.Evidence)" -ForegroundColor DarkGray }
    }
  }
}

Write-Host ""
exit $(if ($script:failed -gt 0) { 1 } else { 0 })