/**
 * Chain layout parity vs pre-spec 42c27bb geometry (#2758 TC-5.2).
 *
 * Deterministic parity capsule replacing the phantom pixel-compare baseline.
 *
 * Identity argument: the chain branch (`computeChatChainPositions`,
 * `computeSubagentChainPositions`) is pure, closed-form math — no d3-force,
 * no randomness, no wall-clock inputs — and rounds 2–16 static-grep constraint
 * receipts verify it is unmodified since pre-spec commit 42c27bb. Unchanged
 * pure functions ⇒ executing HEAD's chain math IS executing 42c27bb's chain
 * math ⇒ formula-derived goldens below ARE pre-spec goldens.
 *
 * (#2764 ST-1: the standalone ToolsNode was removed — the right-side tools
 * column golden was deleted with it; the subagent goldens below are unchanged.)
 *
 * Goldens are HAND-DERIVED from the documented closed form
 *   y_next = y_prev + (prev.height ?? DEFAULT_NODE_HEIGHT) + CHAIN_GAP
 * (layout.ts:115, documented at layout.ts:49) with constants frozen at
 * layout.ts:56/62/65/70 (CHAIN_GAP=28, DEFAULT_NODE_HEIGHT=360,
 * CHAIN_X_CENTER=0, CHAIN_TOP_Y=0) — they are written as literals, NOT
 * generated by invoking the SUT.
 *
 * READ-ONLY constraint honored: this file is the ONLY change in the capsule;
 * layout.ts / useMissionMonitor.ts / MissionMonitorPanel.tsx untouched.
 */
import { describe, it, expect } from 'vitest';
import {
  computeChatChainPositions,
  computeSubagentChainPositions,
  CHAIN_GAP,
  CHAIN_TOP_Y,
  CHAIN_X_CENTER,
  DEFAULT_NODE_HEIGHT,
  SUBAGENT_CHAIN_X,
  SUBAGENT_GAP,
  SUBAGENT_NODE_MAX_WIDTH,
} from '../layout';

describe('Chain layout parity vs pre-spec 42c27bb geometry (#2758 TC-5.2)', () => {
  it('freezes the pre-spec chain constants', () => {
    // layout.ts:56 / :62 / :65 / :70 — frozen #2743-scaled chain geometry.
    expect(CHAIN_GAP).toBe(28);
    expect(DEFAULT_NODE_HEIGHT).toBe(360);
    expect(CHAIN_X_CENTER).toBe(0);
    expect(CHAIN_TOP_Y).toBe(0);
  });

  it('chat chain golden: single-session measured-height stacking matches the documented closed form', () => {
    // Hand-derived from layout.ts:115:
    //   a1 @ y=0 (CHAIN_TOP_Y)
    //   a2 @ y = 0 + 360 + 28 = 388
    //   a3 @ y = 388 + 314 + 28 = 730 (a3 unmeasured → NEXT node would use 360)
    const positions = computeChatChainPositions([
      { id: 'a1', sessionId: 's-a', height: 360 },
      { id: 'a2', sessionId: 's-a', height: 314 },
      { id: 'a3', sessionId: 's-a' },
    ]);

    // Literal golden — position-exact, theme-independent.
    expect(positions.get('a1')).toEqual({ x: 0, y: 0 });
    expect(positions.get('a2')).toEqual({ x: 0, y: 388 });
    expect(positions.get('a3')).toEqual({ x: 0, y: 730 });
  });

  it('chat chain golden: multi-session chains are independent (each starts at CHAIN_TOP_Y)', () => {
    // Per-session grouping (layout.ts:102–117): s-b's fresh chain starts its
    // own stack at CHAIN_TOP_Y; s-a positions are unchanged by s-b's arrival.
    const positions = computeChatChainPositions([
      { id: 'a1', sessionId: 's-a', height: 360 },
      { id: 'a2', sessionId: 's-a', height: 314 },
      { id: 'a3', sessionId: 's-a' },
      { id: 'b1', sessionId: 's-b', height: 200 },
    ]);

    // s-b chain top: independent of s-a's accumulated y.
    expect(positions.get('b1')).toEqual({ x: 0, y: 0 });
    // s-a unchanged vs the single-session golden above.
    expect(positions.get('a1')).toEqual({ x: 0, y: 0 });
    expect(positions.get('a2')).toEqual({ x: 0, y: 388 });
    expect(positions.get('a3')).toEqual({ x: 0, y: 730 });
  });

  it('is deterministic across repeated invocations', () => {
    // Guards future nondeterminism creeping into the chain branch: identical
    // inputs must yield deep-equal Maps on every invocation.
    const agents = [
      { id: 'a1', sessionId: 's-a', height: 360 },
      { id: 'a2', sessionId: 's-a', height: 314 },
      { id: 'a3', sessionId: 's-a' },
      { id: 'b1', sessionId: 's-b', height: 200 },
    ];

    const firstParents = computeChatChainPositions(agents);
    const secondParents = computeChatChainPositions(agents);

    expect([...secondParents.entries()]).toEqual([...firstParents.entries()]);
    expect(secondParents.size).toBe(firstParents.size);
  });

  // ── #2762 ST-4 (R-7): depth-1 flat parity vs the frozen closed form ────────
  //
  // computeSubagentChainPositions was generalized to recursive subtree-band
  // allocation. R-7 HARD REQUIREMENT: a depth-1-only graph MUST produce
  // positions IDENTICAL to today's closed form
  //   x = SUBAGENT_CHAIN_X − index × (SUBAGENT_NODE_MAX_WIDTH + SUBAGENT_GAP)
  //   y = parent chat node y
  // — byte-identical literals below, NOT derived by re-implementing the SUT.

  it('#2762 R-7: depth-1 subagent chain golden matches the frozen closed form (literal −564/−1128/−1692)', () => {
    // One chat parent, three dispatches — literal goldens hand-derived from
    // SUBAGENT_CHAIN_X = −564 and the lane step 540 + 24 = 564.
    const parents = computeChatChainPositions([
      { id: 'a1', sessionId: 's-a', height: 360 },
    ]);
    const positions = computeSubagentChainPositions(
      [
        { id: 'subagent-c0', parentId: 'a1', index: 0 },
        { id: 'subagent-c1', parentId: 'a1', index: 1 },
        { id: 'subagent-c2', parentId: 'a1', index: 2 },
      ],
      parents,
    );

    expect(positions.get('subagent-c0')).toEqual({ x: -564, y: 0 });
    expect(positions.get('subagent-c1')).toEqual({ x: -1128, y: 0 });
    expect(positions.get('subagent-c2')).toEqual({ x: -1692, y: 0 });
    // Constant equivalence for the closed form (frozen #2745 values).
    expect(SUBAGENT_CHAIN_X).toBe(-564);
    expect(SUBAGENT_NODE_MAX_WIDTH + SUBAGENT_GAP).toBe(564);
  });

  it('#2762 R-7: every depth-1 parent restarts the closed form at SUBAGENT_CHAIN_X with its own y', () => {
    // Two chat parents: each parent's index-0 dispatch sits at −564 aligned to
    // ITS OWN chain y — the band walk is per-parent and never shifts one
    // parent's lanes because of another parent's dispatches.
    const parents = computeChatChainPositions([
      { id: 'a1', sessionId: 's-a', height: 360 },
      { id: 'a2', sessionId: 's-a', height: 314 },
    ]);
    const positions = computeSubagentChainPositions(
      [
        { id: 'subagent-a1-0', parentId: 'a1', index: 0 },
        { id: 'subagent-a1-1', parentId: 'a1', index: 1 },
        { id: 'subagent-a2-0', parentId: 'a2', index: 0 },
        { id: 'subagent-a2-1', parentId: 'a2', index: 1 },
        { id: 'subagent-a2-2', parentId: 'a2', index: 2 },
      ],
      parents,
    );

    // a1 y=0; a2 y = 0 + 360 + 28 = 388.
    expect(positions.get('subagent-a1-0')).toEqual({ x: -564, y: 0 });
    expect(positions.get('subagent-a1-1')).toEqual({ x: -1128, y: 0 });
    expect(positions.get('subagent-a2-0')).toEqual({ x: -564, y: 388 });
    expect(positions.get('subagent-a2-1')).toEqual({ x: -1128, y: 388 });
    expect(positions.get('subagent-a2-2')).toEqual({ x: -1692, y: 388 });
  });

  it('#2762 R-7: non-contiguous dispatch indexes still land on the literal closed-form lane', () => {
    // The historical formula used the RAW index value (x = −564 − index×564);
    // the band walk must preserve that exact lane even with gaps.
    const parents = new Map([['a1', { x: CHAIN_X_CENTER, y: 100 }]]);
    const positions = computeSubagentChainPositions(
      [
        { id: 'subagent-g0', parentId: 'a1', index: 0 },
        { id: 'subagent-g5', parentId: 'a1', index: 5 },
      ],
      parents,
    );

    expect(positions.get('subagent-g0')).toEqual({ x: -564, y: 100 });
    expect(positions.get('subagent-g5')).toEqual({ x: -564 - 5 * 564, y: 100 });
  });
});
