/**
 * Chain layout parity vs pre-spec 42c27bb geometry (#2758 TC-5.2).
 *
 * Deterministic parity capsule replacing the phantom pixel-compare baseline.
 *
 * Identity argument: the chain branch (`computeChatChainPositions`,
 * `computeToolsChainPositions`, `computeSubagentChainPositions`) is pure,
 * closed-form math — no d3-force, no randomness, no wall-clock inputs — and
 * rounds 2–16 static-grep constraint receipts verify it is unmodified since
 * pre-spec commit 42c27bb. Unchanged pure functions ⇒ executing HEAD's chain
 * math IS executing 42c27bb's chain math ⇒ formula-derived goldens below ARE
 * pre-spec goldens.
 *
 * Goldens are HAND-DERIVED from the documented closed form
 *   y_next = y_prev + (prev.height ?? DEFAULT_NODE_HEIGHT) + CHAIN_GAP
 * (layout.ts:115, documented at layout.ts:49) with constants frozen at
 * layout.ts:56/62/65/70 (CHAIN_GAP=28, DEFAULT_NODE_HEIGHT=360,
 * CHAIN_X_CENTER=0, CHAIN_TOP_Y=0) — they are written as literals, NOT
 * generated by invoking the SUT.
 *
 * READ-ONLY constraint honored: this file is the ONLY change in the capsule;
 * layout.ts / useMissionMonitor.ts / MissionMonitorPanel.tsx untouched.
 */
import { describe, it, expect } from 'vitest';
import {
  computeChatChainPositions,
  computeToolsChainPositions,
  CHAIN_GAP,
  CHAIN_TOP_Y,
  CHAIN_X_CENTER,
  DEFAULT_NODE_HEIGHT,
} from '../layout';

describe('Chain layout parity vs pre-spec 42c27bb geometry (#2758 TC-5.2)', () => {
  it('freezes the pre-spec chain constants', () => {
    // layout.ts:56 / :62 / :65 / :70 — frozen #2743-scaled chain geometry.
    expect(CHAIN_GAP).toBe(28);
    expect(DEFAULT_NODE_HEIGHT).toBe(360);
    expect(CHAIN_X_CENTER).toBe(0);
    expect(CHAIN_TOP_Y).toBe(0);
  });

  it('chat chain golden: single-session measured-height stacking matches the documented closed form', () => {
    // Hand-derived from layout.ts:115:
    //   a1 @ y=0 (CHAIN_TOP_Y)
    //   a2 @ y = 0 + 360 + 28 = 388
    //   a3 @ y = 388 + 314 + 28 = 730 (a3 unmeasured → NEXT node would use 360)
    const positions = computeChatChainPositions([
      { id: 'a1', sessionId: 's-a', height: 360 },
      { id: 'a2', sessionId: 's-a', height: 314 },
      { id: 'a3', sessionId: 's-a' },
    ]);

    // Literal golden — position-exact, theme-independent.
    expect(positions.get('a1')).toEqual({ x: 0, y: 0 });
    expect(positions.get('a2')).toEqual({ x: 0, y: 388 });
    expect(positions.get('a3')).toEqual({ x: 0, y: 730 });
  });

  it('chat chain golden: multi-session chains are independent (each starts at CHAIN_TOP_Y)', () => {
    // Per-session grouping (layout.ts:102–117): s-b's fresh chain starts its
    // own stack at CHAIN_TOP_Y; s-a positions are unchanged by s-b's arrival.
    const positions = computeChatChainPositions([
      { id: 'a1', sessionId: 's-a', height: 360 },
      { id: 'a2', sessionId: 's-a', height: 314 },
      { id: 'a3', sessionId: 's-a' },
      { id: 'b1', sessionId: 's-b', height: 200 },
    ]);

    // s-b chain top: independent of s-a's accumulated y.
    expect(positions.get('b1')).toEqual({ x: 0, y: 0 });
    // s-a unchanged vs the single-session golden above.
    expect(positions.get('a1')).toEqual({ x: 0, y: 0 });
    expect(positions.get('a2')).toEqual({ x: 0, y: 388 });
    expect(positions.get('a3')).toEqual({ x: 0, y: 730 });
  });

  it('tools column golden: x = parent.x + AGENT_NODE_MAX_WIDTH + TOOLS_GAP, y mirrors parent', () => {
    // Parent chat chain identical to the single-session golden above.
    const parents = computeChatChainPositions([
      { id: 'a1', sessionId: 's-a', height: 360 },
      { id: 'a2', sessionId: 's-a', height: 314 },
      { id: 'a3', sessionId: 's-a' },
    ]);

    // Golden derived from layout.ts:230 with the documented maxWidth(540) +
    // gap(24) derivation (layout.ts:128–137): parent a2 → {x: 0+540+24=564,
    // y mirrors parent 388}. Tools column constant TOOLS_CHAIN_X ≡ 564.
    const tools = computeToolsChainPositions(
      [{ id: 'tools-a2', parentId: 'a2' }],
      parents,
    );

    expect(tools.get('tools-a2')).toEqual({ x: 564, y: 388 });
  });

  it('is deterministic across repeated invocations', () => {
    // Guards future nondeterminism creeping into the chain branch: identical
    // inputs must yield deep-equal Maps on every invocation.
    const agents = [
      { id: 'a1', sessionId: 's-a', height: 360 },
      { id: 'a2', sessionId: 's-a', height: 314 },
      { id: 'a3', sessionId: 's-a' },
      { id: 'b1', sessionId: 's-b', height: 200 },
    ];
    const tools = [{ id: 'tools-a2', parentId: 'a2' }];

    const firstParents = computeChatChainPositions(agents);
    const secondParents = computeChatChainPositions(agents);

    expect([...secondParents.entries()]).toEqual([...firstParents.entries()]);
    expect(secondParents.size).toBe(firstParents.size);

    const firstTools = computeToolsChainPositions(tools, firstParents);
    const secondTools = computeToolsChainPositions(tools, secondParents);
    expect([...secondTools.entries()]).toEqual([...firstTools.entries()]);
  });
});
